stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - chaos-test
  - cleanup
  - deploy

aws-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 755 ./script/aws
    - ./script/aws

  artifacts:
    paths:
      - aws/

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - aws-cluster
  script: 
   - echo "deploying OpenEBS on AWS"
   - chmod 775 ./script/infra-setup
   - ./script/infra-setup
  
  artifacts:
    paths:
      - aws-openebs/

percona-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/percona-app-deploy
   - ./script/percona-app-deploy

  artifacts:
    paths:
      - aws-openebs/

mongo-aws-deploy:
  image: atulabhi/kops:v8
  stage: stateful-apps-deploy
  dependencies:
    - openebs-aws-deploy
  script: 
   #- echo "jobs-AWS-Started"
   - chmod 775 ./script/mongo-app-deploy
   - ./script/mongo-app-deploy

  artifacts:
    paths:
      - aws-openebs/

Litmus-Chaos:
  image: atulabhi/kops:v8
  dependencies:
    - openebs-aws-deploy
  stage: chaos-test
  script:
   - echo " Introducing-Chaos"
   - mkdir ~/.kube
   - cp  aws-openebs/config ~/.kube/config 
   - kubectl create -f https://raw.githubusercontent.com/atulabhi/litmus/v0.7-RC1/apps/percona/chaos/openebs_volume_replica_failure/run_litmus_test.yaml
   - chmod 755 ./script/chaos
   - ./script/chaos

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: cleanup
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
